export const FETCH_API_START = 'FETCH_API';
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
export const FETCH_API_FAILURE = 'FETCH_API_FAILURE';


export const SET_AUTH_USER_DATA_SUCCES = 'SET_AUTH_USER_DATA_SUCCES';