// MAP CONSTS
export const FETCH_API_START = 'FETCH_API';
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
export const FETCH_API_FAILURE = 'FETCH_API_FAILURE';
export const FETCH_USER_PINS_START = 'FETCH_USER_PINS_START';
export const FETCH_USER_PINS_SUCCES = 'FETCH_USER_PINS_SUCCES';
export const FETCH_USER_PINS_FAILURE = 'FETCH_USER_PINS_FAILURE';


// AUTH CONSTS
export const SET_AUTH_USER_DATA_SUCCES = 'SET_AUTH_USER_DATA_SUCCES';


export const FETCH_USER_BOOK_START = "FETCH_USER_BOOK_START";
export const FETCH_USER_BOOK_FAILURE = 'FETCH_USER_BOOK_FAILURE';
export const FETCH_USER_BOOK_SUCCESS = 'FETCH_USER_BOOK_SUCCESS';

