export const VIEWPORT_CHANGED = 'VIEWPORT_CHANGED'
export const GET_COORDS_REQUEST = 'GET_COORDS_REQUEST'
export const GET_COORDS_SUCCES = 'GET_COORDS_SUCCES'
export const GET_COORDS_FAILURE = 'GET_COORDS_FAILURE'